version: '3.1'
services:
  db:
    image: mariadb:latest
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: root
  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 3005:80
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - db
  api:
    build: .
    volumes:
      - ./api:/var/www/html
    ports:
      - 3000:80
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
